---
on: 
  push:
    branch: testing

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: Create BOSH Release

    steps:
    - name:  git checkout
      users: actions/checkout

    - name: bosh create-release
      id:   release
      uses: jhunt/bosh-create-release@v1
      with:
        version: 1.2.3
