---
on: 
  push:
    branch: testing

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Create BOSH Release
    steps:
    - name: bosh create-release
      id:   release
      uses: jhunt/bosh-create-release@v1
      with:
        version: 1.2.3
